<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from de.systopia.sqltasks/xml/schema/CRM/Sqltasks/SqlTasksGlobalToken.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:3346c30abcba98762c3cec1e21877476)
 */
use CRM_Sqltasks_ExtensionUtil as E;

/**
 * Database access object for the SqlTasksGlobalToken entity.
 */
class CRM_Sqltasks_DAO_SqlTasksGlobalToken extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_sqltasks_global_token';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique SqlTasks GlobalToken ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * token name
   *
   * @var string
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $token_name;

  /**
   * Token data type
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $data_type;

  /**
   * Token value
   *
   * @var string
   *   (SQL type: longtext)
   *   Note that values will be retrieved from the database as a string.
   */
  public $token_value;

  /**
   * Token description
   *
   * @var string
   *   (SQL type: text)
   *   Note that values will be retrieved from the database as a string.
   */
  public $description;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_sqltasks_global_token';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Sql Tasks Global Tokens') : E::ts('Sql Tasks Global Token');
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('ID'),
          'description' => E::ts('Unique SqlTasks GlobalToken ID'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_sqltasks_global_token.id',
          'table_name' => 'civicrm_sqltasks_global_token',
          'entity' => 'SqlTasksGlobalToken',
          'bao' => 'CRM_Sqltasks_DAO_SqlTasksGlobalToken',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'token_name' => [
          'name' => 'token_name',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Token name'),
          'description' => E::ts('token name'),
          'required' => TRUE,
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_sqltasks_global_token.token_name',
          'table_name' => 'civicrm_sqltasks_global_token',
          'entity' => 'SqlTasksGlobalToken',
          'bao' => 'CRM_Sqltasks_DAO_SqlTasksGlobalToken',
          'localizable' => 0,
          'add' => NULL,
        ],
        'data_type' => [
          'name' => 'data_type',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Token data type'),
          'description' => E::ts('Token data type'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_sqltasks_global_token.data_type',
          'default' => '1',
          'table_name' => 'civicrm_sqltasks_global_token',
          'entity' => 'SqlTasksGlobalToken',
          'bao' => 'CRM_Sqltasks_DAO_SqlTasksGlobalToken',
          'localizable' => 0,
          'html' => [
            'type' => 'Select',
          ],
          'pseudoconstant' => [
            'optionGroupName' => 'sqltasks_global_token_data_type',
            'optionEditPath' => 'civicrm/admin/options/sqltasks_global_token_data_type',
          ],
          'add' => NULL,
        ],
        'token_value' => [
          'name' => 'token_value',
          'type' => CRM_Utils_Type::T_LONGTEXT,
          'title' => E::ts('Token value'),
          'description' => E::ts('Token value'),
          'required' => FALSE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_sqltasks_global_token.token_value',
          'table_name' => 'civicrm_sqltasks_global_token',
          'entity' => 'SqlTasksGlobalToken',
          'bao' => 'CRM_Sqltasks_DAO_SqlTasksGlobalToken',
          'localizable' => 0,
          'html' => [
            'type' => 'TextArea',
          ],
          'add' => NULL,
        ],
        'description' => [
          'name' => 'description',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Token description'),
          'description' => E::ts('Token description'),
          'required' => FALSE,
          'rows' => 4,
          'cols' => 60,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_sqltasks_global_token.description',
          'table_name' => 'civicrm_sqltasks_global_token',
          'entity' => 'SqlTasksGlobalToken',
          'bao' => 'CRM_Sqltasks_DAO_SqlTasksGlobalToken',
          'localizable' => 0,
          'html' => [
            'type' => 'TextArea',
          ],
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'sqltasks_global_token', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'sqltasks_global_token', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
