site_name: SQL Tasks
repo_url: https://github.com/systopia/de.systopia.sqltasks
theme:
  name: material

nav:
- 'Home': index.md
- 'Installation': installation.md
- 'Configuration': configuration.md
- 'Usage': usage.md
- 'Example': example.md
- 'Global Tokens': global-tokens.md
- 'Templates': templates.md
- 'Integrations':
  - 'CiviRules': civirules.md
  - 'Custom': custom-integrations.md
- 'Security considerations': security-considerations.md
- 'Known issues': known-issues.md

markdown_extensions:
- attr_list
- admonition
- def_list
- codehilite
- toc:
    permalink: true
- pymdownx.superfences
- pymdownx.inlinehilite
- pymdownx.tilde
- pymdownx.betterem
- pymdownx.mark
